server:
  port: 8080

spring:
  application:
    name: cgic-gateway
  redis:
    database: 4
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: 8
      min-idle: 0
      max-idle: 8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

#ribbon:
#  ReadTimeout: 12000
#  ConnectTimeout: 12000
#  eureka:
#    enabled: true
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 90000

zuul:
  addHostHeader: true
  routes:
    cgic-platform:
      path: /cgpf/**
      service-id: cgic-platform
    cgic-oauth:
      path: /oauth/**
      service-id: cgic-oauth
    cgic-test:
      path: /test/**
      service-id: cgic-test
  semaphore:
    max-semaphores: 300
  sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Origin
  host:
      socket-timeout-millis: 12000
      connect-timeout-millis: 12000

cgic:
  oauth:
    helper:
      user-info-uri: http://localhost:8020/api/user/info
      service-id: cgic-oauth
      enabled: true
      released-path:
        - /info
        - /oauth/oauth/**
        - /swagger/swagger-ui.html
        - /swagger/swagger-resources/**
        - /swagger/webjars/**
        - /swagger/docs/**
security:
  basic:
    enabled: false

